
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/conf/,D:/temp/springconfig/
  application:
    name: config-server
server:
  port: 8888